export default {
  credits: [
    {
      id: 'play_game',
      name: 'Play game 1 hour',
      sign: -1,
      type: 'spend',
      credit: 5,
    },
    {
      id: 'watch_youtube',
      name: 'Watch YouTube 0.5 hour',
      sign: -1,
      type: 'spend',
      credit: 3,
    },
    {
      id: 'screen_time',
      name: 'Screen Time 1 hour',
      sign: -1,
      type: 'spend',
      credit: 3,
    },
    {
      id: 'food',
      name: 'Eat McD',
      sign: -1,
      type: 'spend',
      credit: 3,
    },
    {
      id: 'complaints_from_teacher',
      name: 'Complaints from teacher',
      sign: -1,
      type: 'deduct',
      credit: 10,
    },
    {
      id: 'tell_lies',
      name: 'Tell lies',
      sign: -1,
      type: 'deduct',
      credit: 5,
    },
    {
      id: 'disobey_parents',
      name: 'Disobey parents',
      sign: -1,
      type: 'deduct',
      credit: 5,
    },
    {
      id: 'rude_to_parents',
      name: 'Rude to parents',
      sign: -1,
      type: 'deduct',
      credit: 5,
    },
    {
      id: 'fighting_with_sibling',
      name: 'Fighting with sibling',
      sign: -1,
      type: 'deduct',
      credit: 5,
    },
    {
      id: 'fighting_with_mummy',
      name: 'Fighting with mummy',
      sign: -1,
      type: 'deduct',
      credit: 5,
    },
    {
      id: 'being_difficult',
      name: 'Being difficult',
      sign: -1,
      type: 'deduct',
      credit: 3,
    },
    {
      id: 'play_game_extended',
      name: 'Play game - took extra time',
      sign: -1,
      type: 'deduct',
      credit: 3,
    },
    {
      id: 'drink_water_less',
      name: 'Drink < 1 bottle of water',
      sign: -1,
      type: 'deduct',
      credit: 2,
    },
    {
      id: 'not_greeting_others',
      name: 'Not greeting others',
      sign: -1,
      type: 'deduct',
      credit: 2,
    },
    {
      id: 'wakeup_tantrum',
      name: 'Wake up trantrum',
      sign: -1,
      type: 'deduct',
      credit: 2,
    },
    {
      id: 'being_annoying',
      name: 'Being annoying',
      sign: -1,
      type: 'deduct',
      credit: 1,
    },
    {
      id: 'compliments_from_teacher',
      name: 'Compliments from teacher',
      sign: 1,
      type: 'earn',
      credit: 10,
    },
    {
      id: 'practice_piano_exceed_15min',
      name: 'Practice piano > 15 min',
      sign: 1,
      type: 'earn',
      credit: 3,
    },
    {
      id: 'reading_books_x3',
      name: 'Reading 3x books',
      sign: 1,
      type: 'earn',
      credit: 3,
    },
    {
      id: 'do_homework',
      name: 'Do homework properly',
      sign: 1,
      type: 'earn',
      credit: 3,
    },
    {
      id: 'maths_exceed_90',
      name: 'Maths homework exceeds 90%',
      sign: 1,
      type: 'earn',
      credit: 3,
    },
    {
      id: 'maths_100',
      name: 'Maths homework 100%',
      sign: 1,
      type: 'earn',
      credit: 3,
    },
    {
      id: 'skip_rope_200',
      name: 'Skip rope x 200',
      sign: 1,
      type: 'earn',
      credit: 2,
    },
    {
      id: 'help_mummy',
      name: 'Help Mummy',
      sign: 1,
      type: 'earn',
      credit: 1,
    },
    {
      id: 'help_papa',
      name: 'Help Papa',
      sign: 1,
      type: 'earn',
      credit: 1,
    },
  ],
  colors: [
    '#fc8181',
    '#f56565',
    '#e53e3e',
    '#c53030',
    '#f6ad55',
    '#ed8936',
    '#dd6b20',
    '#c05621',
    '#f6e05e',
    '#ecc94b',
    '#d69e2e',
    '#b7791f',
    '#68d391',
    '#48bb78',
    '#38a169',
    '#2f855a',
    '#4fd1c5',
    '#38b2ac',
    '#319795',
    '#2c7a7b',
    '#4299e1',
    '#3182ce',
    '#2b6cb0',
    '#2c5282',
    '#667eea',
    '#5a67d8',
    '#4c51bf',
    '#434190',
    '#9f7aea',
    '#805ad5',
    '#6b46c1',
    '#553c9a',
  ],
  creatures: [
    {
      id: 'molo',
      filename: 'molo.png',
      name: 'Molo',
      path: require('~/assets/img/tolos/molo.png')
    },
    {
      id: 'bubble',
      filename: 'bubble.png',
      name: 'Bubble',
      path: require('~/assets/img/tolos/bubble.png')
    },
    {
      id: 'candy_monster',
      filename: 'candy_monster.png',
      name: 'Candy Monster',
      path: require('~/assets/img/tolos/candy_monster.png')
    },
    {
      id: 'catrox',
      filename: 'catrox.png',
      name: 'Catrox',
      path: require('~/assets/img/tolos/catrox.png')
    },
    {
      id: 'loop',
      filename: 'loop.png',
      name: 'Loop',
      path: require('~/assets/img/tolos/loop.png')
    },
    {
      id: 'lumpy_pudding',
      filename: 'lumpy_pudding.png',
      name: 'Lumpy Pudding',
      path: require('~/assets/img/tolos/lumpy_pudding.png')
    },
    {
      id: 'nono',
      filename: 'nono.png',
      name: 'Nono',
      path: require('~/assets/img/tolos/nono.png')
    },
    {
      id: 'orx',
      filename: 'orx.png',
      name: 'Orx',
      path: require('~/assets/img/tolos/orx.png')
    },
    {
      id: 'panglima',
      filename: 'panglima.png',
      name: 'Panglima',
      path: require('~/assets/img/tolos/panglima.png')
    },
    {
      id: 'peddy',
      filename: 'peddy.png',
      name: 'Peddy',
      path: require('~/assets/img/tolos/peddy.png')
    },
    {
      id: 'slom',
      filename: 'slom.png',
      name: 'Slom',
      path: require('~/assets/img/tolos/slom.png')
    },
    {
      id: 'yambil',
      filename: 'yambil.png',
      name: 'Yambil',
      path: require('~/assets/img/tolos/yambil.png')
    },
  ], 
}